name: CI - React + Jest + Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Jest Unit Tests
        run: npm run test:jest --if-present

      - name: Start app and run Cypress tests
        run: npm run test:e2e:run
